# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
target 'trafficbuddy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
# Pods for Sesh
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
target 'trafficbuddy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
target 'trafficbuddyTests' do
    inherit! :search_paths
    # Pods for testing
  end
end