

export const locations = {
    "Alba": "AB", 
    "Arad": "AR", 
    "Arges": "AG", 
    "Bacău": "BC", 
    "Bihor": "BH", 
    "Bistrița-Năsăud": "BN", 
    "Botoșani": "BT", 
    "Brașov": "BV", 
    "Brăila": "BR", 
    "București": "B", 
    "Buzău": "BZ", 
    "Caraș-Severin": "CS", 
    "Călărași": "CL", 
    "Cluj": "CJ", 
    "Constanța": "CT", 
    "Covasna": "CV", 
    "Dâmbovița": "DB", 
    "Dolj": "DJ", 
    "Galați": "GL", 
    "Giurgiu": "GR", 
    "Gorj": "GJ", 
    "Harghita": "HR", 
    "Hunedoara": "HD", 
    "Ialomița": "IL", 
    "Iași": "IS", 
    "Ilfov": "IF", 
    "Maramureș": "MM", 
    "Mehedinți": "MH", 
    "Mureș": "MS", 
    "Neamț": "NT", 
    "Olt": "OT", 
    "Prahova": "PH", 
    "Satu Mare": "SM", 
    "Sălaj": "SJ", 
    "Sibiu": "SB", 
    "Suceava": "SV", 
    "Teleorman": "TL", 
    "Timiș": "TM", 
    "Tulcea": "TL", 
    "Vaslui": "VS", 
    "Vâlcea": "VL", 
    "Vrancea": "VR", 
}

